# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TaskToDoApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TaskToDoApp
  pod 'IBAnimatable'
  pod 'Alamofire', '~> 5.2'
  pod 'RAMAnimatedTabBarController'
  pod 'Material', '~> 3.1.0'
  pod 'MaterialComponents'
  pod 'PKHUD'
end
